@startuml seq
    title Диаграмма последовательности взаимодействий систем и сервисов при получении заказа из постамата
    actor Client as c
participant Postamat as p
participant Server as s
    database "БД" as db

c++
c->p++: показывает QR-code для получения или вводит код из смс
        p -> s++: Отправка введенных клиентом данных


        s -> db++ : Запрос данных клиента и заказа
  
        s <--db--: Получение данных по заказу

        s -> s: Проверка данных и статуса заказа


alt заказ оплачен
s --> p: номер ячейки для открывания
s--
p --> c: показать сообщение на экране об открытии ячейки и открыть ячейку с полученным номером
p--
else заказ не оплачен
s++
 p <-- s--: показать сумму к оплате
p++

c <-- p: вывести сообщение о необходимости оплаты и сумму
p -> p: активировать терминал оплаты

alt клиент делает оплату
c->p: проведит платеж с терминала
p-> s++: отправка платежа
s->s: проверка платежа
s->db++: сохранение информации и получение номера ячейки
db -->s: данные по заказу
db--
s-->p: номер ячейки для открывания
s--
p-->c: показать сообщение на экране об открытии ячейки и открыть ячейку с полученным номером
p--
else клиент не оплачивает заказ
c--

p->p++: ждет необходимое время, при отсутствии оплаты деактивирует терминал
p--

end alt

else ошибка с данными заказа

s-->p++: выведи сообщение обратится в поддержку с контактами
s++
c++
s--
p--> c: показать сообщение на экране о необходимости обратится в поддержку и контакты
p--
c--
end alt

  
   
@enduml
